[project]
name = "epub-metadata"
description = "A TUI for editing EPUB metadata"
version = "0.0.0"
authors = [{ name = "Hugo Marotta", email = "humtta@proton.me" }]

license = "MIT"
readme = "README.md"

requires-python = ">=3.14"

dependencies = [
    "ebooklib>=0.20",
    "textual>=8.2.8",
]

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
